# This GitHub workflow deploys Bundle resources (ML resource config and more)
# defined under oh_nytaxi_mlops/resources/*
# and oh_nytaxi_mlops/databricks.yml with staging deployment target configs,
# when PRs are merged into the default branch
name: Bundle Deployment for oh_nytaxi_mlops Staging

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

defaults:
  run:
    working-directory: ./oh_nytaxi_mlops

env:
  ARM_TENANT_ID: ${{ secrets.STAGING_AZURE_SP_TENANT_ID }}
  ARM_CLIENT_ID: ${{ secrets.STAGING_AZURE_SP_APPLICATION_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.STAGING_AZURE_SP_CLIENT_SECRET }}
  

jobs:
  staging:
    concurrency: oh_nytaxi_mlops-staging-bundle-job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: databricks/setup-cli@v0.212.2
      - name: Validate Bundle For Staging
        id: validate
        run: |
          databricks bundle validate -t oh_mlops_staging
      - name: Deploy Bundle to Staging
        id: deploy
        run: |
          databricks bundle deploy -t oh_mlops_staging
